
/**************************************************************
 *	
 *	bottomFeeders, 8 bit, 11025Hz,
 *	1 channel, 3140640 bytes/channel
 *	Total Size: 1 * 3140640 + 4 (header) = 3140684 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Will\Documents\bottomFeeders.wav
 *	Time-stamp: Tue Apr 12 18:57:48 2016
 *	
 **************************************************************/

#ifndef __BOTTOMFEEDERSH__
#define __BOTTOMFEEDERSH__

#define BOTTOMFEEDERSFREQ 11025
#define BOTTOMFEEDERSLEN 3140640

extern const unsigned char bottomFeeders[3140640];

#endif /* __BOTTOMFEEDERSH__ */
