
/**************************************************************
 *	
 *	fleshTear, 8 bit, 11025Hz,
 *	1 channel, 49946 bytes/channel
 *	Total Size: 1 * 49946 + 4 (header) = 49990 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Will\Documents\School\CS2261\Final Project\Project\Assets\fleshTear.wav
 *	Time-stamp: Thu Apr 21 23:47:37 2016
 *	
 **************************************************************/

#ifndef __FLESHTEARH__
#define __FLESHTEARH__

#define FLESHTEARFREQ 11025
#define FLESHTEARLEN 49946

extern const unsigned char fleshTear[49946];

#endif /* __FLESHTEARH__ */
