
/**************************************************************
 *	
 *	sword, 8 bit, 11025Hz,
 *	1 channel, 6087 bytes/channel
 *	Total Size: 1 * 6087 + 4 (header) = 6131 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Will\Documents\sword.wav
 *	Time-stamp: Tue Apr 12 19:14:04 2016
 *	
 **************************************************************/

#ifndef __SWORDH__
#define __SWORDH__

#define SWORDFREQ 11025
#define SWORDLEN 6087

extern const unsigned char sword[6087];

#endif /* __SWORDH__ */
