
/**************************************************************
 *	
 *	undertaleChoir, 8 bit, 11025Hz,
 *	1 channel, 378432 bytes/channel
 *	Total Size: 1 * 378432 + 4 (header) = 378476 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Will\Documents\School\CS2261\Final Project\Project\Assets\undertaleChoir.wav
 *	Time-stamp: Thu Apr 21 00:18:50 2016
 *	
 **************************************************************/

#ifndef __UNDERTALECHOIRH__
#define __UNDERTALECHOIRH__

#define UNDERTALECHOIRFREQ 11025
#define UNDERTALECHOIRLEN 378432

extern const unsigned char undertaleChoir[378432];

#endif /* __UNDERTALECHOIRH__ */
